"""initial schema

Revision ID: 0db51def8e7c
Revises: 
Create Date: 2025-12-13 16:47:47.355121

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0db51def8e7c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_article_category", "news_articles", ["category"], unique=False)
    op.create_index("ix_article_date", "news_articles", ["date"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_article_date", table_name="news_articles")
    op.drop_index("ix_article_category", table_name="news_articles")
    # ### end Alembic commands ###
